create table
  public.award_nominations (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    nominee_name character varying not null,
    slug character varying not null,
    year bigint not null,
    award character varying not null,
    constraint award_nominations_pkey primary key (id, nominee_name, year, award),
    constraint award_nominations_award_fkey foreign key (award) references awards (award_name) on update cascade on delete cascade
  ) tablespace pg_default;